### PR TITLE
More specific description of unacceptable behavior

### PR DESCRIPTION
**Pull request by afilina**
"Appropriateness" is too broad and subjective. There is, however, a lot of documentation on what constitutes toxic behavior.

### CODE REVIEW

**Comment by derickr** [comment]
How would you define "toxic" though? It's also subjective. I'd like to try to make it less subjective.

**Comment by afilina** [comment]
Ok I understand. Can we then take out "inappropriate" instead of replacing it? "Threatening, offensive, or harmful" pretty much covers all the basics and is a bit more specific.

As a conference organizer, some people from abroad consider things inappropriate, but later surprised that in our part of the world that is totally normal. I wouldn't want anyone accidentally breach the code because of differences in culture/upbringing (or be afraid to accidentally do so). Inappropriateness also doesn't imply the intent to harm.

**Comment by johnhunt** [comment]
I completely agree with @afilina , this needs to be very clear - ambiguities won't help anyone here.

**Comment by derickr** [comment]
+1 However, you'd need to re-do the PR, as I've broken the mergability by splitting the document up.

**Pull request closed without merging**
