### PR TITLE
Remove ambiguous 'unethical or professional' clause.

### PR DESCRIPTION
**Pull request by mprelude**
Remove ambiguous 'unethical or unprofessional behavior' clause.

This adds nothing, and only serves as a 'catch all' clause.

It's better to take the route of failing to catch some undesired behavior, and updating the CoC when required.

### CODE REVIEW

**Comment by henrycatalinismith** [comment]
Worth noting that this change was rejected upstream (ContributorCovenant/contributor_covenant#223)

**Comment by mprelude** [comment]
@hnrysmth Upstream language was changed to:
- Other conduct which could reasonably be considered inappropriate in a professional setting

The 'unethical' part was entirely dropped. I don't think either part of the clause is useful, but prefer the upstream language to what we have here.

**Comment by henrycatalinismith** [comment]
Oh hey you're right. I remember now: when I was porting CCv1.4 here, I was about to delete this line. Then I noticed the PHP version was different to the vanilla CC version. I was trying not to trample too much on any PHP-specific patches so I left it but apart from that it's kind of meh either way

**Comment by mprelude** [comment]
I still think there's an ambiguity issue because, well for example I've worked in UK and USA which are culturally similar, but there's things I would happily say in the office in one and not in the other.

Even moreso, people who work in offices will have very different ideas about what professional conduct entails than people who work in warehouses, factories or customer-facing retail.

**Comment by henrycatalinismith** [comment]
For sure man, I get what you're saying. It's tempting and easy for me to react defensively to suggestions like your PR here. And on reflection I don't think this particular patch is such a big deal.

Gotta be careful with cultural relativism in general. Your UK/USA professionalism example's pretty reasonable actually (:+1:). Elsewhere I saw someone suggesting that mainstream acceptance of homophobia in certain countries presents some sort of moral dilemma about rules against homophobia in open source projects (in short, lol no). I only mention this to explain that I'm down with your point, but don't want anyone reading this to get the idea that cultural relativism is a magic button.

If we're at a place with this where everyone is cool with explicit rules against harassment and hate speech, and what's left is details like these, I actually reckon things are looking a lot brighter than they were a while back :smile:

**Comment by mprelude** [comment]
@hnrysmth Absolutely happy with rules against hate speech & harassment as long as they're defined clearly so that no one can be unaware that they're breaking the rules. Discussions I had with Coraline on the matter were interesting.

I'm a sucker for clarity, I think I may have been a lawyer in a past life.

**Comment by derickr** [comment]
Happy to change it to what the contributor covenant has now.

**Comment by mprelude** [comment]
@derickr Great, am closing this PR.

**Pull request closed without merging**
